name: flutter_system_tray
description: A Flutter system tray plugin for macOS.
version: 0.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: FlutterSystemTrayPlugin
